#[개념 정리]
## 9.2 가우시안 혼합
* 가우시안 혼합 모델: 샘플이 파라미터가 알려지지 않은 여러 개의 혼합된 가우시안 분포에서 생성되었다고 가정하는 확률 모델
* GaussianMixture 클래스에 구현됨.
* 기댓값-최적화 알고리즘을 사용함

(1) 기댓값 단계: 샘플을 클러스터에 할당

(2) 최대화 단계: 클러스터를 업데이트

(3) 소프트 클러스터 할당을 사용함

(4) 책임: 클러스터에 속할 추정 확률

### 9.2.1 가우시안 혼합을 사용한 이상치 탐지

* 이상치 탐지는 보통과 많이 다른 샘플을 감지하는 작업

* 사용할 밀도 임곗값을 정해야 한다.

* 특이치 탐지는 이상치 탐지와 달리 이상치로 오염되지 않은 깨끗한 데이터셋에서 훈련한다.

### 9.2.2 클러스터 개수 선택하기

* BIC, AIC

*확률: 파라미터 theta인 확률 모델이 주어지면, 미래 출력 x가 얼마나 그럴듯한지 설명한다.

* 가능도: 출력 x를 알고 있을 때, 특정 파라미터 값 theta가 얼마나 그럴듯한지 설명한다.

### 9.2.3 베이즈 가우시안 혼합 모델

*BayesGaussianMixture 클래스 사용

*클러스터 개수는 n_components를 최적의 클러스터 개수보다 크다고 믿을 만한 값으로 지정한다.

* 자동으로 불필요한 클러스터를 제거

### 9.2.4 이상치 탐지와 특이치 탐지를 위한 다른 알고리즘

* 이상치 탐지와 특이치 탐지 전용으로 사용할 수 있는  다른 알고리즘

* PCA :보통 샘플의 재구성 오차와 이상치의 재구성 오차를 비교하면 일반적으로 후자가 훨씬 크다.

* Fast-MCD :EllipticEnvelope 클래스에서 구현된 이 알고리즘은 이상치 감지에 유용

* 아이솔레이션 포레스트 :특히 고차원 데이터셋에서 이상치 감지를 위한 효율적인 알고리즘

* LOF :이상치 탐지에 좋음

* on-class SVM :특이치 탐지에 잘 맞는다.

#[코드필사]

In [1]:
import numpy as np
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=1000,noise=0.05)

In [2]:
from sklearn.mixture import GaussianMixture

gm = GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

GaussianMixture(n_components=3, n_init=10)

In [3]:
gm.weights_

array([0.59585437, 0.2103595 , 0.19378613])

In [4]:
gm.means_

array([[ 0.5231348 ,  0.22972598],
       [-0.72657634,  0.57006037],
       [ 1.77283324, -0.03797058]])

In [5]:
gm.covariances_

array([[[ 0.17243888, -0.10613117],
        [-0.10613117,  0.29143465]],

       [[ 0.05893076,  0.06616227],
        [ 0.06616227,  0.08980944]],

       [[ 0.04282357,  0.05440978],
        [ 0.05440978,  0.08335269]]])

In [6]:
gm.converged_

True

In [7]:
gm.n_iter_

17

In [8]:
gm.predict(X)

array([0, 2, 0, 0, 2, 1, 0, 0, 0, 0, 2, 0, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0,
       0, 0, 2, 2, 2, 2, 0, 2, 1, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 2,
       0, 2, 2, 0, 2, 0, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 1, 0, 2, 0, 1,
       0, 0, 1, 2, 0, 2, 0, 2, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2,
       2, 2, 1, 0, 0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0,
       0, 1, 2, 0, 1, 2, 1, 0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       2, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0,
       1, 0, 2, 2, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 2,
       2, 1, 0, 2, 0, 0, 0, 1, 1, 2, 1, 2, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 2, 0, 2, 2, 0, 1, 2, 0, 2,
       0, 2, 1, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 1, 0,
       1, 0, 2, 1, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 1,

In [9]:
gm.predict_proba(X)

array([[1.00000000e+000, 1.05004491e-077, 1.10410657e-030],
       [1.98886640e-001, 7.87799540e-176, 8.01113360e-001],
       [1.00000000e+000, 3.79840830e-024, 4.31922346e-104],
       ...,
       [1.00000000e+000, 1.68801184e-021, 4.80764931e-110],
       [1.00000000e+000, 7.69374648e-060, 2.99885906e-045],
       [1.42529589e-004, 9.99857470e-001, 1.06296448e-256]])

In [10]:
X_new, y_new = gm.sample(6)
X_new

array([[ 0.70794154,  0.06283251],
       [ 0.15360612,  0.68906704],
       [ 0.15742424,  0.67434556],
       [ 0.44919484,  0.53079381],
       [-0.76069512,  0.44838846],
       [-0.72277825,  0.38214102]])

In [11]:
y_new

array([0, 0, 0, 0, 1, 1])

In [12]:
gm.score_samples(X)

array([-1.58503489e+00, -1.41686424e+00, -1.61986137e+00, -1.59148533e+00,
       -1.06834586e+00, -1.03909010e+00, -1.49215480e+00, -2.20801128e+00,
       -1.96910894e+00, -1.56923791e+00, -4.30794047e-01, -1.53143227e+00,
       -1.43972610e+00, -2.24484594e+00, -6.64223232e-01, -7.78594986e-01,
       -2.06195822e+00, -1.73801016e+00, -3.75544495e+00, -1.17483638e+00,
       -2.52539982e-02, -1.91576573e+00, -1.61486075e+00, -1.43770553e+00,
       -3.31911151e-01,  7.76416449e-02, -2.27926901e+00, -3.27692306e-01,
       -1.46511862e+00, -1.57031598e+00, -2.52549253e-01, -1.92908068e+00,
       -5.38876136e-01, -1.48196541e+00, -9.64717410e-01,  1.38138993e-01,
       -1.74234063e+00, -6.51951375e-01, -1.48760331e+00, -1.80301690e+00,
       -1.52731990e+00, -1.73266249e+00, -2.65011898e-01, -1.47717090e+00,
       -1.66926859e+00, -4.20213514e-01, -7.43803791e-01, -1.60198608e+00,
       -1.52444466e+00, -1.80665949e+00, -1.58856389e+00, -4.58589427e-01,
       -1.68114784e+00, -

In [13]:
densities = gm.score_samples(X)
density_threshold = np.percentile(densities,4)
anomalies = X[densities < density_threshold]

In [14]:
gm.bic(X)

np.float64(2736.7159048847643)

In [15]:
gm.aic(X)

np.float64(2653.284065142068)

In [16]:
from sklearn.mixture import BayesianGaussianMixture
bgm = BayesianGaussianMixture(n_components=10, n_init=10)
bgm.fit(X)
np.round(bgm.weights_,2)

/usr/local/lib/python3.12/dist-packages/sklearn/mixture/_base.py:269: ConvergenceWarning: Best performing initialization did not converge. Try different init parameters, or increase max_iter, tol, or check for degenerate data.
  warnings.warn(


array([0.15, 0.11, 0.14, 0.13, 0.12, 0.12, 0.15, 0.09, 0.  , 0.  ])