# [개념 정리]

## 8. 텍스트 분석
* NLP : 머신이 인간의 언어를 이해하고 해석하는데에 중점
* Test Mining : 비정형 텍스트에서 의미있는 정보를 추출하는데에 중점
* 텍스트 분류, 감정분석, 텍스트요약, 텍스트 군집화

##1.  텍스트 분석 이해
* 텍스트 분석: 비정형 데이터인 텍스트를 분석하는 것
* 피처 벡터화 or 피처 추출 : 텍스를 기반의 다수의 피처를 추출하고 이 피처에 단 빈도수와 같은 숫자값을 부여-> 벡터값으로 표현
* 텍스트-> 피처 벡터화 방법: BOW or Word2Vec 방법
* 텍스트 분석 수행 과정
  1) 텍스트 사전 준비 작업 -> 텍스트 전처리
  2) 피처 벡터화/추출
  3) ML 모델 수립 및 학습/예측/평가

### 파이썬 기반의 NLP, 텍스트 분석 패키지
* NLTK: 대표적인 NLP 패키지, 수행속도가 아쉬움
* Gensim : 토픽 모델링 분약에서 두각을 나타냄
* SpaCy

## 2. 텍스트 사전 준비 작업
1) 클렌징
  - 분석에 방해가 되는 불필요한 문자, 기호 등을 사전에 제거하는 작업
2) 토큰화
  - 문장 토큰화: 문서-> 문장으로 분리 (sent_tokenize를 이용)

  - 단어 토큰화 : 문장-> 단어로 분리, 단어의 순서가 중요하지 않은 경우에 사용

if) 문장을 단어별로 토큰화 -> 문맥적 의미 무시 -> 해결책 :n-gram(연속된 n개의 단어를 하나의 토큰화 단위로 분리해 내는것

3) 스톱워드 제거
* 스톱워드: 분석에 큰 의마가 없는 단어를 지칭함.

4) Stemming and Lemmatization
* 문법적 똔느 의미적으로 변형하는 단어의 원형을 찾는것
* Stemming : 원형 단어로 변화하는 일반적인 방법, 원래 단어에서 일부 철자가 훼손된 어근 단어를 추출'
* Lemmatization : 정확한 철자로 된 어근의 단어를 찾음

## 3. BOW
* BOW 모델: 문서가 가지는 모든 단어를 문맥이나 순서를 무시하고 일괄적으로 단어에 빈도값을 부여해 피처 값을 추출하는 모델
* 문제점: 문맥 의미 반영 무족, 희소 행렬 문제 발생

### Bow 피처 벡터화
* 피처 벡터화 : 텍스트는 특정 의미를 가진 숫자혀 값으로 벡터값을 변환하는 것
* 방식: 카운트 기반의 벡터화 + TF-IDF 기반의 벡터화

### 사이킷런의 count 및 tf-ids 벡터 구현
* countVectorizor : 카운트 기반의 벡터화를 구현하는 클래스를 말함.
* max_df, min_df, max_feautres, stop_words, n_gram_range, analyzer, token_pattern, botkenizer

### BOW 벡터화를 위한 희소 행렬
* 희소 행렬: 대규모 행렬의 대부분의 갑슬 00우로 차지하는 행렬
* 대표적인 방법 :COO + CSR 형식

### 최소 행렬-COO 형식
*scipy
* 사이파이의 coo_matrix 클래스를 이용해  coo see down

### 희소행렬 -CSR 형식
*CSR : 반복적인 위치 데이터를 사용해야하는 배열을



---
# 코드 필사


In [3]:
from nltk import sent_tokenize
import nltk
#nltk.download('punkt')
nltk.download('punkt_tab')
text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
               You can see it out your window or on your television. \
               You feel it when you go to work, or go to church or pay your taxes.'

sentences = sent_tokenize(text=text_sample)
print(type(sentences),len(sentences))
print(sentences)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


In [5]:
from nltk import word_tokenize

sentence='The Matrix is everywhere its all around us, here even in this room.'
words=word_tokenize(sentence)
print(type(words),len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [6]:
from nltk import word_tokenize, sent_tokenize
#여러 개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화하게 만드는 함수 생성
def tokenize_text(text):
  #문장별로 분리 토큰
  sentences=sent_tokenize(text)
  #분리된 문장별 단어 토큰화
  word_tokens=[word_tokenize(sentence) for sentence in sentences]
  return word_tokens

#여러 문장에 대해 문장별 단어 토큰화 수행.
word_tokens=tokenize_text(text_sample)
print(type(word_tokens),len(word_tokens))
print(word_tokens)



<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


In [7]:
#스몰 워드 제거
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
print('영어 stop words 갯수:',len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 갯수: 198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']


In [10]:
import nltk

stopwords=nltk.corpus.stopwords.words('english')
all_tokens=[]
#위 예제에서 3개의 문장별로 얻은 word_tokens list에 대해 스톱워드를 제거하는 반복문
for sentence in word_tokens:
  filtered_words=[]
  #개별 문장별로 토큰화된 문장 list에 대해 스톱워드를 제거하는 반복문
  for word in sentence:
    #소문자로 모두 변환합니다.
    word=word.lower()
    #토큰화된 개별 단어가 스톱 워드의 단어에 포함되지 않으면 word_tokens에 추가
    if word not in stopwords:
      filtered_words.append(word)
    all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['matrix', 'everywhere', 'around', 'us', ',', '

In [11]:
from nltk.stem import LancasterStemmer
stemmer=LancasterStemmer()

print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('works'),stemmer.stem('amusing'))
print(stemmer.stem('happier'),stemmer.stem('works'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('works'),stemmer.stem('fanciest'))

work work work
amus work amus
happy work happiest
fant work fanciest


In [13]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemma=WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'),lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'),lemma.lemmatize('fanciest','a'))

amuse amuse amuse
happy happy
fancy fancy


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [14]:
import numpy as np

dense=np.array([[3,0,1],[0,2,0]])

In [15]:
from scipy import sparse

#0이 아닌 데이터 추출
data=np.array([3,1,2])

#행위치와 열위치를 각각 배열로 생성
row_pos=np.array([0,0,1])
col_pos=np.array([0,2,1])

#sparse 패키지의 coo_matrix를 이용해 COO 형식으로 희소 행렬 생성
sparse_coo=sparse.coo_matrix((data, (row_pos, col_pos)))

In [16]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [17]:
[[0, 0, 1, 0, 0, 5], [1, 4, 0, 3, 2, 5], [0, 6, 0, 3, 0, ], [2, 0, 0, 0, 0, ], [0, 0, 0, 7, 0,8], [1, 0, 0, 0, 0, 0] ]

[[0, 0, 1, 0, 0, 5],
 [1, 4, 0, 3, 2, 5],
 [0, 6, 0, 3, 0],
 [2, 0, 0, 0, 0],
 [0, 0, 0, 7, 0, 8],
 [1, 0, 0, 0, 0, 0]]

In [18]:
from scipy import sparse

dense2=np.array([[0,0,1,0,0,5],
                 [1,4,0,3,2,5],
                 [0,6,0,3,0,0],
                 [2,0,0,0,0,0],
                 [0,0,0,7,0,8],
                 [1,0,0,0,0,0]])

#0이 아닌 데이터 추출
data2=np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

#행 위치와 열 위치를 각각 array로 생성
row_pos=np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos=np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

#COO 형식으로 변환
sparse_coo=sparse.coo_matrix((data2, (row_pos, col_pos)))

# 행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성
row_pos_ind=np.array([0,2,7,9,10,12,13])

#CSR 형식으로 변환
sparse_csr=sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [20]:
dense3=np.array([[0,0,1,0,0,5],
                 [1,4,0,3,2,5],
                 [0,6,0,3,0,0],
                 [2,0,0,0,0,0],
                 [0,0,0,7,0,8],
                 [1,0,0,0,0,0]])

coo=sparse.coo_matrix(dense3)
csr=sparse.coo_matrix(dense3)