##1.1 인공지능, 머신러닝과 딥러닝
- 인공지능 : 인간의 지능을 모방하여 사람이 하는일을 컴퓨터가 할 수 있도록 하는 기술
- 인공지능 : 머신러닝+딥러닝
1) 머신러닝 : 주어진 데이터 인간 처리<- 데이터 특징을 스스로 추출X
2) 딥러닝: 인간이 하던 작업 생략, 컴퓨터가 스스로 분석한 후에 답을 도출

##1.2 머신러닝이란
### 1.2.1 머신러닝 학습 과정
-과정: 학습단계 -> 예측단계
-머신러닝 구성요소 : 데이터 + 모델

### 1.2.2 머신러닝 학습 알고리즘
1) 지도학습 : 정답을 알려주고 컴퓨터가 학습
2) 비지도학습: 정답을 알려주짙, 범주화하여 예측
3) 강화학습: 보상이 커지는 행동을 자주, 줄어드는 행동을 덜하도록 학습

##1.3 딥러닝이란
-딥러닝: 심층 신경망 이론을 기반으로 고안된 머신러닝 방법의 일종

### 1.3.1 딥러닝 학습 과정
-데이터 준비 -> 모델 정의(신경망 생성) -> 모델 컴파일(활성화 함수, 손실함수, 옵티마이저 선택) -> 모델 훈련(배치,에포크 선택) -> 모델 예측
- 핵심구성요소 : 신경망과 역전파 <- 심층 신경망을 사용

### 1.3.2 딥러닝 학습 알고리즘
1) 지도학습- 합성곱 신경망(이미지분류),순환신경망(시계열분류)
2) 비지도학습- 워드임베딩, 군집
3) 전이학습
4) 사전 학습 모델
5) 강화학습

##2.1 파이토치 개요
### 2.1.1 파이토치 특징 및 장점
- GPU, Tensor, 동적신경망(훈련 반복시-> 네트워크 변경이 가능한 신경망 의미)
-파이토치 장점: 단순함, 낮은CPU활용, 직관적인 인터페이스

### 2.1.2 파이토치의 아키텍처
- 파이토치 API -> 파이토치 엔진(다차원 텐서와 자동미분을 처리) -> 텐서에 대한 연산 처리
1) 파이토치 API : 사용자 인터페이스 제공, 실제계산 X
  - torch,autograd(자동미분), torch.nn(신경망 구축), torch.multiprocesssing, torch.utils(DataLoader)
2) 파이토치 엔진
3) 연산처리 : 모든 계산 수행 , tensor가 핵심

## 2.2 파이토치 기초 문법
### 2.2.1 텐서 다루기
-텐서 생성 및 변환: torch.numpy()
-텐서의 인덱스 조작
-텐서의 연산 및 차원 조작 : 텐서간의 타입이 다르면 연산이 불가능, 텐서 조작 view, stack,cat, t, transpose이용

### 2.2.2 데이터 준비
- 파이썬 라이브러리를 이용, 파이토치에서 제공하는 데이터를 이용하는 방법
- 커스텀 데이터셋: 데이터를 한번에 다 부르지 않고 조금씩 나누어 불러서 사용하는 방식
- 토치비전: 파이포치에서 제공하는 데이터셋이 모여있는 패키지
- 데이터셋 다운: request 라이브러리 설치

### 2.2.3모델 정의
- 계층, 모듈, 모델
-nn.Module()을 상속하여 정의 하는 방법 : init(), forward()함수 이용
-nn.Sequential

### 2.2.4 모델의 파라미터 정의
- 손실함수 : BCELoss, CrossEntropy, MSELoss
- 옵티마이저
- 학습률 스케줄러: 미리 지정한 횟수의 에포크를 지날때마다 학습률을 감소시켜줌.
-지표: 훈련과 테스트 단계 모니터링

### 2.2.5 모델 훈련
1) optimizer.zero_grad() 메서지 : 기울기 초기화
2) backward() : 새로운 기울기 값이 이전 기울기 값에 누적하여 계산

### 2.2.6 모델 평가
1) 함수를 이용하여 평가
2) 모듈을 이용하여 평가

### 2.2.7 훈련과정 모니터링
- model.train() : 훈련 데이터셋에서 사용하며 모델 훈련이 진행됨.
- model.eval(): 모델 평가시 모든 노드 사용


In [1]:
import torch
print(torch.tensor([[1,2],[3,4]])) # 2차원 형태의 텐서 생성
print(torch.tensor([[1,2],[3,4]], device="cuda:0")) # GPU에 텐서 생성
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64)) # dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
temp=torch.tensor([[[1,2],[3,4]]])
print(temp.numpy()) # 텐서를 ndarray로 변환

temp=torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp.to("cpu").numpy()) # GPU상의 텐서를 CPU의 텐서로 변환한 후 ndarray로 변환

[[[1 2]
  [3 4]]]
[[1 2]
 [3 4]]


In [4]:
temp=torch.FloatTensor([1,2,3,4,5,6,7]) #파이토치로 1차원 벡터 생성
print(temp[0], temp[1], temp[-1]) # 인덱스로 접근
print('--------')
print(temp[2:5], temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
--------
tensor([3., 4., 5.]) tensor([5., 6.])


In [5]:
v=torch.tensor([1,2,3]) #길이가 3인 벡터 생성
w=torch.tensor([3,4,6])
print(w-v) #길이가 같은 벡터 간 뺄셈 연산

tensor([2, 2, 3])


In [6]:
temp=torch.tensor([[1,2],[3,4]]) #2*2 행렬 생성
print(temp.shape)
print('---------------')
print(temp.view(4,1)) #2*2행렬을 4*1로 변환
print('---------------')
print(temp.view(-1)) #2*2행렬을 1차원 벡터로 변환
print('---------------')
print(temp.view(1,-1))
print('---------------')
print(temp.view(-1,1))

torch.Size([2, 2])
---------------
tensor([[1],
        [2],
        [3],
        [4]])
---------------
tensor([1, 2, 3, 4])
---------------
tensor([[1, 2, 3, 4]])
---------------
tensor([[1],
        [2],
        [3],
        [4]])


In [7]:
#pip install pandas

import pandas as pd

import torch

data = pd.read_csv('../class2.csv')

x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()

y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

import pandas as pd

import torch

from torch.utils.data import Dataset

from torch.utils.data import DataLoader

class CustomDataset(Dataset):

    def __init__(self, csv_file):

        self.label = pd.read_csv(csv_file)

    def __len__(self):

        return len(self.label)
    
    def __getitem__(self, idx):

        sample = torch.tensor(self.label.iloc[idx,0:3]).int()

        label = torch.tensor(self.label.iloc[idx,3]).int()

        return sample, label

tensor_dataset = CustomDataset('../covtype.csv')

dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True)

    for i, data in enumerate(dataset,0):

      print(i, end='')

      batch=data[0]

      print(batch.size())

In [8]:
!pip install requests

import torchvision.transfroms as transforms

mnist_transform=transform.Compose([

  transforms.ToTensor(),
  
  transforms.Normalize((0.5), (1.0,))

])

from torchvision.datasets import MNIST

import requests

downloda_root='MNIST_DATASET' # 내려받을 경로

train_dataset=MNIST(download_root, transform=mnist_transform, train=True, download=True) #훈련 데이터 셋
valid_dataset=MNIST(download_root, transform=mnist_transform, train=True, download=True) #검증 데이터 셋
test_dataset=MNIST(download_root, transform=mnist_transform, train=True, download=True) #테스트 데이터 셋

In [9]:
#model=nn.Linear(in_features=1, out_features=1, biase=True)

class MLP(Module):

    def __init__(self, inputs):

      super(MLP,self).__init__()

      self.layer=Linear(inputs,1) #계층 정의

      self.activation=Sigmoid() #활성화 함수 정의

    def forward(self,X):

      X=self.layer(X)

      X=self.activation(X)

      return X



    


In [11]:
import torch.nn as nn
class MLP(nn.Module):
  def __init__(self):
    super(MLP, self).__init__()
    self.layer1=nn.Sequential(
        nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer2=nn.Sequential(
        nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer3=nn.Sequential(
        nn.Linear(in_features=30*5*5, out_features=10, bias=True),
        nn.ReLU(inplace=True))

    def forward(self, x):
      x=self.layer1(x)
      x=self.layer2(x)
      x=x.view(x.shape[0], -1)
      x=self.layer3(x)
      return x

model=MLP() # 모델에 대한 객체 생성

print('Printing childern\n--------')
print(list(model.children()))
print('\n\nPrinting Modules\n-------')
print(list(model.modules()))

Printing childern
--------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
-------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=750, out_features=10, bias=True

In [12]:
def MLP(in_features=1, hidden_features=20, out_features=1):
  hidden=nn.Linear(in_features=in_features, out_features=hidden_features, bias=True)
  activation=nn.ReLU()
  output=nn.Linear(in_features=hidden_features, out_features=out_features, bias=True)
  net=nn.Sequential(hidden, activation, output)
  return net

    from torch.optim import optimizer

    criterion=torch.nn.MSELoss()

    optimizer=torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

    schedular=torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer, lr_lambda=lambda epoch: 0.95 ** epoch)

    for epoch in range(1, 100+1): # 에포크 수만큼 데이터를 반복하여 처리

      for x,y in dataloader: # 배치 크기만큼 데이터를 가져와서 학습 진행

        optimizer.zero_grad()

    loss_fn(model(x),y).backward()

    optimizer.step()

    schedular.step()

    for epoch in range(100):

      yhat=model(x_train)

      loss=criterion(yhat, y_train)

      optimizer.zero_grad() #오차가 중첩적으로 쌓이지 않도록 초기화

      loss.backward()

      optimizer.step()

In [14]:
pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 24.1 MB/s eta 0:00:00


    import torch
    
    import torchmetrics

    preds=torch.randn(10,5).softmax(dim=1)

    target=torch.randint(5,(10,))

    acc=torchmetrics.functional.accuracy(preds, target)

    import torch

    import torchmetrics

    metric=torchmetrics.Accuracy() #모델 평가 초기화

    n_batches=10

    for i in range(n_batches):

      preds=torch.randn(10,5).softmax(dim=1)

      target=torch.randint(5, (10,))

      acc=metric(preds, target)

      print(f'Accuracy on batch {i}:{acc}') #현재 배치에서 모델 평가

    acc=metric.compute()

    print(f'Accuracy on all data: {acc}') #모든 배치에서 모델 평가

pip install tensorboard

    import torch

    from torch.utils.tensorboard import SummaryWriter

    wrtier=SummaryWriter('code') #모니터링에 필요한 값들이 저장될 위치

    for epoch in range(num_epochs):
    
      model.train() # 학습모드로 전환
      
      batch_loss=0.0
      
      for i, (x,y) in enumerate(dataloader):
      
        x,y=x.to(device).float(), y.to(device).float()
        
        outputs=model(x)

        loss=criterion(outputs, y)

        writer.add_scaler('Loss', loss, epoch) #스칼라 값을 기록

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

      wrtier.close() #SummaryWriter가 더이상 필요하지 않으면 close()메서드 호출

    model.eval() #검증모드로 전환

    with torch.no_grad():

      valid_loss=0

      for x,y in valid_dataloader:

        outputs=model(x)

        loss=F.cross_entropy(outputs, y.long().squeeze())

        valide_loss += float(loss)

        y_hat +=[outputs]

    valid_loss= valid_loss/len(valid_loader)