##[개념정리]

### 1. 사이킷런
* 파이썬 머시런닝 라이브러리
* 쉽고 가장 파이썬 스러운 API를 제공, 매우 많은 환경에서 사용되는 성숙한 라이브러리

지도학습
    * 레이블 데이터로 모델 학습 -> 별도의 테스트 데이터 세트에서 미지의 레이블 예측
    * 학습 데이터 세트: 학습을 위해 주어진 데이터 세트 & 테스트 데이터 세트: 모델의 예측 성능을 평가하기 위해 별도로 주어진 데이터 세트

### 2.

1. 새로운 쥬피터 노트북 생성, 사이킷런에서 사용할 모듈을 임포트
   * sklearn.datasets 내의 모듈 
   * sklearn.tree 내의 모듈
   * sklearn.model_selection
   * 하이퍼 파라미터 : 머신러닝 알고리즘별로 최적의 학습을 위해 직접 입력하는 파라미터 통칭-> 머신러닝 알고리즘의 성틍을 튜닝
   * 데이터 생성: load_iris(), ML알고리즘 : 의사결정트리, 구현: DesicionTreeClassifier 적용

2. 학습용 데이터와 테스트용 데이터를 분리
    * train_test_split() API 제공
    * test_size 파라미터 입력값의 비율로 쉽게 분할
    * random_state : 호출할때마다 같은 데이터 세트를 생성하기 위한 난수 값

3. 의사결정트리를 이용해 학습과 예측을 수행
    * DesicionTreeClassifier의 fit() 메서드 : 학습을 수행
    * predict() 메서드 : 테스트 데이터 세트에서 예측값 반환

4. 의사결정 트리 기반의 DescisonTreeClassifier의 예측 성능 평가
    * 정확도 : 예측결과가 실제 레이블 값과 얼마나 정확하게 맞는지 평가하는 지표 -> accuracy_score() 함수 이용
    * accuracy_score(실제 레이블 데이터 세트, 예측 레이블 데이터 세트)

### 3.사이킷런의 기반 프레임워크 익히기
 * ML 모델 학습 : fit(), 학습된 모델 예측 : predict()
 * Classifier(분류 알고리즘을 구현하는 클래스)&Regressor(회귀 알고리즘 구현)-> Estimator 클래스

비지도학습 
 * fit() & transform() 적용
 * fit() : 입력데이터의 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업
 * transform() : 입력데이터의 차원변환, 클러스터링, 피처 추출등의 실제 작업

사이킷런 주요 모델 : sklearn.datasets, sklearn.preprocessing, sklearn.metrics, sklearn.linear_model, sklearn.tree

머신러닝 모델 구축 과정 : 피처 처리-> ML 알고리즘 학습/예측 수행 -> 모델 평가-> 반복

표본데이터의 키
* data, target, target_names, feature_names, DESCR로 구성됨

### 4. Model Selection 모듈 소개
* model_selection: 학습데이터와 테스트 데이터 세트를 분리 or 교차 검증 분할 및 평가, Estimator의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수와 클래스를 제공
* train_test_split() : 학습/테스트 데이터 세트 분리

#### 교차검증
- 과접합: 모델이 학습 데이터에만 과도하게 최적화되어, 실제 예측을 다른 데이터로 수행할 경우에는 예측 성능이 과도하게 떨어진다. -> 교차검증을 이용해서 문제점을 개선
- 즉) 본고사를 치르기 전에 모의고사를 여러번 보는 것
- 별도의 여러 세트로 구성된 학습 데이터 세트와 검증데이터세트에서 학습과 평가를 수행

#### k 폴드 교차 검증
- k개의 데이터 폴드 세트를 만들어서 k번만큼 각 폴트 세트에 학습과 검증 평가를 반복적으로 수행하는 방법

#### cross_val_score()
1. 폴드세트 설정
2. for 루프에서 반복으로 학습 및 테스트 데이터의 인덱스를 추출
3. 반복적으로 학습과 예측을 수행하고 예측 성능을 반환
-> cross_val_score(estimator, X, y, scoring: 예측 성능 평가 지표 기술, cv: 교차 검증 폴드 수)

#### cross_validate()
: 여러 개의 평가지표를 반환할 수 있음.

#### GridSearchCV 
: classifier나 regressor와 같은 알고리즘에서 사용되는 하이퍼 파라미터를 순차적으로 입력하여서 최적을 파라미터를 도축할 수 있음

In [2]:
#pip install sickit-learn=1.0.2

In [1]:
import sklearn

print(sklearn.__version__)

1.6.1


In [2]:
# train_test_split()함수를 이용해서 데이터세트를 학습데이터와 테스트 데이터로 분리
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd

#붓꽃 데이터 세트를 로딩
iris=load_iris()

#iris.data는 Iris 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있다.
iris_data=iris.data

#iris.target은 붓꽃 데이터 세으트에서 레이블 데이터를 numpy로 가지고 있다.
iris_label=iris.target
print('iris target 값:',iris_label)
print('iris target 명:',iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target 값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [4]:
# 2. 학습용 데이터와 테스트용 데이터를 분리
X_train, X_test, y_train, y_test=train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [5]:
# 3. 의사결정트리를 이용해 학습과 예측을 수행
# DecisionTreeClassifier 객체 생성
df_clf=DecisionTreeClassifier(random_state=11)

In [6]:
# 학습 수행
df_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [7]:
#학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred=df_clf.predict(X_test)

In [8]:
# 4. 의사결정 트리 기반의 DescisonTreeClassifier의 예측 성능 평가
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


### 3.사이킷런의 기반 프레임워크 익히기
 * ML 모델 학습 : fit(), 학습된 모델 예측 : predict()
 * Classifier(분류 알고리즘을 구현하는 클래스)&Regressor(회귀 알고리즘 구현)-> Estimator 클래스

비지도학습 
 * fit() & transform() 적용
 * fit() : 입력데이터의 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업
 * transform() : 입력데이터의 차원변환, 클러스터링, 피처 추출등의 실제 작업

사이킷런 주요 모델 : sklearn.datasets, sklearn.preprocessing, sklearn.metrics, sklearn.linear_model, sklearn.tree

머신러닝 모델 구축 과정 : 피처 처리-> ML 알고리즘 학습/예측 수행 -> 모델 평가-> 반복

표본데이터의 키
* data, target, target_names, feature_names, DESCR로 구성됨

In [9]:
from sklearn.datasets import load_iris

iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [10]:
keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [11]:
print('\n feature_names의 type:', type(iris_data.feature_names))
print('feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print('target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print('data의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:', type(iris_data.target))
print('target의 shape:', iris_data.target.shape)
print(iris_data.target)


 feature_names의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 

### 4. Model Selection 모듈 소개
* model_selection: 학습데이터와 테스트 데이터 세트를 분리 or 교차 검증 분할 및 평가, Estimator의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수와 클래스를 제공
* train_test_split() : 학습/테스트 데이터 세트 분리

In [12]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 세트으로 예측 수행
pred=dt_clf.predict(train_data)
print('예측 정확도:',accuracy_score(train_label, pred))

예측 정확도: 1.0


In [13]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

dt_clf=DecisionTreeClassifier()
iris_data=load_iris()

X_train,X_test,y_train,y_test=train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [14]:
dt_clf.fit(X_train, y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도:0.9556


In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=150)

#5개의 폴드 세트로 분리되는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [26]:
n_iter=0

#KFold 객체의 split()를 호출하면 폴드별 학습용, 검증용 테스트의 로우 인덱스를 array로 변환
for train_index, test_index in kfold.split(features):
    #kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train,X_test=features[train_index], features[test_index]
    y_train,y_test=label[train_index], label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred=dt_clf.predict(X_test)
    n_iter +=1
    #반복시마다 정확도 측정
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기:{2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('\#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)

#개별 iteration별 정확도를 합하여 평균 정확도 계싼
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도:1.0, 학습 데이터 크기:120, 검증 데이터 크기: 30
\#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도:1.0, 학습 데이터 크기:120, 검증 데이터 크기: 30
\#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도:0.9, 학습 데이터 크기:120, 검증 데이터 크기: 30
\#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도:0.9333, 학습 데이터 크기:120, 검증 데이터 크기: 30
\#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도:0.7333, 학습 데이터 크기:120, 검증 데이터 크기: 30
\#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9133199999999999


#### k 폴드 교차 검증
* 5폴드 교차 검증
  1. 학습과 교차를 위한 데이터 세트로 변경하여 5번 수행
  2. 5개의 평균한 결과를 가지고 예측 성능 평가
    
* KFold클래스를 이용해서 보이기
1. Kfold로 Kfold(n_splits=5)로 객체 생성
2. KFold 객체의 split()을 이용해서 데이터 분리

#### Stratified K 폴드
: 불균형한 분포를 가진 레이블 데이터 집합을 위한 K폴드 방식
-> StratifiedKFold 클래스 이용하기
* 여기의 split() 메서드 인자로 피처 데이터 세트 뿐만 아니라 레이블 데이터 세트도 반드시 필요함.

In [27]:
import pandas as pd
iris=load_iris()
iris_df=pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [33]:
kfold=KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
    n_iter +=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차 검증:{0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증:1
학습 레이블 데이터 분포:
 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    50
Name: count, dtype: int64
## 교차 검증:2
학습 레이블 데이터 분포:
 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    50
Name: count, dtype: int64
## 교차 검증:3
학습 레이블 데이터 분포:
 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
2    50
Name: count, dtype: int64


In [36]:
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter+=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차 검증:{0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증:1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증:2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증:3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64


In [45]:
# StratifiedKFold를 이용해서 데이터를 분리하여 교차검증하기
dt_clf=DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#StratifiedKFold의 split() 호출시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
    #split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train,X_test=features[train_index], features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred=dt_clf.predict(X_test)

    #반복시마다 정확도 측정
    n_iter +=1
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('\n#{0} 교차 검증 정확도: {1}, 학습데이터 크기:{2}, 검증데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('\n#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)

#교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:',np.round(cv_accuracy,4))
print('\n## 평균 검증 정확도:',np.round(np.mean(cv_accuracy),4))


#1 교차 검증 정확도: 0.98, 학습데이터 크기:100, 검증데이터 크기: 50

#1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도: 0.94, 학습데이터 크기:100, 검증데이터 크기: 50

#2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도: 0.98, 학습데이터 크기:100, 검증데이터 크기: 50

#3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]

## 평균 검증 정확도: 0.9667


#### cross_val_score()
1. 폴드세트 설정
2. for 루프에서 반복으로 학습 및 테스트 데이터의 인덱스를 추출
3. 반복적으로 학습과 예측을 수행하고 예측 성능을 반환
-> cross_val_score(estimator, X, y, scoring: 예측 성능 평가 지표 기술, cv: 교차 검증 폴드 수)

* 이 API 내부에서는 estimator의 학습, 예측, 평가를 시켜줌.
* cv로 지정된 횟수만큼 scoring 파라미터로 지정된 평가 지표를 평가 결과을 배열로 반환

#### cross_validate()
: 여러 개의 평가지표를 반환할 수 있음.

In [48]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

#성능지표를 accuracy, 교차 검증 3개
scores=cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores,4))
print('평균 검증 정확도:', np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


* 하이퍼 파라미터는 머신러닝 알고리즘을 구성하는 주요 요소 -> 알고리즘 예측 성능을 개선 할 수 있음

#### GridSearchCV 
: classifier나 regressor와 같은 알고리즘에서 사용되는 하이퍼 파라미터를 순차적으로 입력하여서 최적을 파라미터를 도축할 수 있음
1. 데이터 세트를 cross-validataion을 위한 학습/데이터 세트로 자동을 분할
2. 하이퍼 파라미터 그리드에 기술된 파라미터를 순차적으로 적용
3. 최적의 파라미터를 찾음

->GridSearchCV(estimator, param_grid: key+ 리스트값을 가지는 딕셔너리, scoring, cv, reflit)
* params 칼럼: 수행할때마다 적용한 개별 하이퍼 파라미터값
* rank_test_score: 하이퍼파라미터별로 성능이 좋은 score 순위
* mean_Test_socre은 개별 파라미터별로 CV의 폴딩 테스트 세트에 대해 총 수행한 평가 평균값

In [49]:
grid_parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [51]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#데이터 로딩하고 학습데이터와 테스트 데이터 분리
iris_data=load_iris()
X_train,X_test,y_train,y_test=train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree=DecisionTreeClassifier()

## 파라미터를 딕셔너리 형태로 설정
parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [55]:
import pandas as pd

#param_grid의 하이퍼 파라미터를 3개의 train,test set fold로 나누어 테스트 수행 설정.
## refit=True가 default임. True이면 가장 좋은 파라미터 설정으로 재학습시킴.
grid_dtree=GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

#붓꼿 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

#GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [58]:
print('GridSearchCV 최적 파라미터:',grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [60]:
#GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator=grid_dtree.best_estimator_

#GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도:0.9667
