#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [1]:
import numpy as np

A=np.random.random((5,3))
B=np.random.random((3,2))
print(np.dot(A,B))

[[1.34120442 0.46261892]
 [1.47154426 0.44302107]
 [1.74221204 0.41901431]
 [1.20349247 0.33429498]
 [1.35824086 0.46365168]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [5]:
A=np.arange(10)
A[(A>3) & (A<8)]*=-1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9(-1+0+1+2+3) 10(0+1+2+3+4)

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

3(존재하지 않음)
6(잘못된 비교 연산)



#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. nan
2. 0
3. value error

In [6]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-6-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-6-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-6-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [26]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
common_value=np.intersect1d(Z1,Z2)
print('Z1:',Z1)
print('Z2:',Z2)
print('common value:',common_value)

Z1: [0 7 8 7 2 2 3 7 4 2]
Z2: [6 2 0 6 3 2 2 4 1 3]
common value: [0 2 3 4]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False.

이유 : nan != 1j이므로


In [10]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-10-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [12]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [31]:
A=np.random.randint(5)
B=np.random.randint(5)
C=np.add(A,B)
D=np.negative(A)
E=np.divide(D,2)
F=np.multiply(C,E)
print(F)

-8.0


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [23]:
A=np.random.uniform(0, 5, size=5)
print(A//1)

[1. 2. 3. 4. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [14]:
create_matrix=np.random.randint(0,5,25).reshape((5,5))
print(create_matrix)

[[3 1 4 2 3]
 [4 4 1 1 2]
 [1 2 0 2 3]
 [0 1 1 0 2]
 [1 2 3 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [15]:
create_vector=np.random.randint(1,11,10)
print(create_vector)
print(np.sort(create_vector))

[10  4  4 10  7  9  6  9  9  2]
[ 2  4  4  6  7  9  9  9 10 10]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [18]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [54]:
# 카르테시안 좌표 생성 (x, y)
cartesian_coordinates = np.random.uniform(-10, 10, (10, 2))

# 각 좌표에 대해 r (거리)와 θ (각도) 계산
r = np.sqrt(cartesian_coordinates[:, 0]**2 + cartesian_coordinates[:, 1]**2)  # 거리
theta = np.arctan2(cartesian_coordinates[:, 1], cartesian_coordinates[:, 0])  # 각도

polar_coordinates = np.column_stack((r, theta))
print("Polar Coordinates (r, θ):\n", polar_coordinates)

Polar Coordinates (r, θ):
 [[ 3.64411314  1.56896317]
 [ 1.62986372 -3.03492295]
 [10.03664381  0.45199529]
 [ 7.66748739  1.62208644]
 [ 5.01107424 -3.130738  ]
 [11.41639045  0.72778305]
 [10.98610891  0.73135529]
 [ 3.99730974 -0.36307957]
 [ 9.38913562 -2.27366347]
 [ 8.7106546   1.43277578]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [33]:
Z=np.random.randint(1,20,10)
Z[Z.argmax()]=0
print(Z)

[10 13  9  0  7 19  4 15  8 10]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [38]:
Z = np.arange(100)
v = np.random.uniform(0,100)
distance_Zv=np.abs(Z-v)

closet_index=np.argmin(distance_Zv)
print(Z[closet_index])

4


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [45]:
Z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
  print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [41]:
n = 4
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),4)
print(Z)

[[0. 0. 4. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 4.]
 [0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [49]:
#1st column

Z = np.random.randint(0,10,(3,3))
print(Z)

#sorting 후
print(Z[np.argsort(Z[:,0])])

[[2 0 2]
 [1 2 0]
 [6 1 1]]
[[1 2 0]
 [2 0 2]
 [6 1 1]]


In [50]:
#2nd column

Z = np.random.randint(0,10,(3,3))
print(Z)

#sorting 후
print(Z[np.argsort(Z[:,1])])

[[7 1 4]
 [8 9 7]
 [1 7 1]]
[[7 1 4]
 [1 7 1]
 [8 9 7]]


In [51]:
#3rd column

Z = np.random.randint(0,10,(3,3))
print(Z)

#sorting 후
print(Z[np.argsort(Z[:,2])])

[[7 3 1]
 [4 4 9]
 [1 4 2]]
[[7 3 1]
 [1 4 2]
 [4 4 9]]
